apiVersion: v1
kind: Service
metadata:
  name: remix-weather-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: remix-weather-app
    app: remix-weather-app