name: Build & Deploy to Test

on:
  pull_request:
    branches:
      - main
    paths:
      - 'app/**'
      - 'kubernetes/**'

permissions:
  id-token: write
  contents: read

env:
  ACR_NAME: ${{ secrets.ACR_NAME }}
  RESOURCE_GROUP: cst8918-final-project-group-3
  AKS_CLUSTER_NAME: aks-test

jobs:
  build-and-deploy-test:
    name: Build Image & Deploy to Test AKS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to Azure Container Registry
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_URI="${{ env.ACR_NAME }}.azurecr.io/remix-weather-app:${{ github.sha }}"
          docker build -t $IMAGE_URI ./app
          docker push $IMAGE_URI

      - name: Set AKS Credentials
        run: |
          az aks get-credentials \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ env.AKS_CLUSTER_NAME }} \
            --overwrite-existing

      - name: Deploy to Test AKS Cluster
        run: |
          sed -i 's|IMAGE_PLACEHOLDER|'${{ env.ACR_NAME }}'.azurecr.io/remix-weather-app:'${{ github.sha }}'|g' kubernetes/deployment.yaml
          kubectl apply -f kubernetes/